= {lab_name}

Welcome to Red Hat One 2026 and this exciting, hands-on, lab experience. Throughout this lab, we will explore a wide variety of tools available to analyze, search and debug OpenShift cluster data to find patterns, issues and other useful information that will help you engage with your customers.

This lab does not use a running OpenShift cluster, it instead focus on offline debugging using common and easy to collect files our customers provide when they run into issues.

image::openshift-logo.svg[openshift-logo,100%,100%]

== Lab structure

This lab is broken down into 9 unique modules that explore a variety of tools. There is no specific ordering to move between each module, but we do recommend you review *Module 1* and *Module 2* first.

You must review *Module 6* before moving on to the rest of the OVN sections.

Once you have reviewed *Module 1* and *Module 2*, feel free to continue to *Module 3* or pick one that interests you the most.

. *Module 1* introduces all of the tools we will be using
. *Module 2* does a deeper dive on the functionality in the *omc* tool
. *Module 3* uses *ocp_insights.py* to triage an OpenShift Cluster
. *Module 4* uses *etcd-ocp-diag.py* to review etcd logs for performance related issues
. *Module 5* uses the *kubectl-dev_tool* to explore a cluster with an overloaded OpenShift API
. *Module 6* introduces the OVN environment
. *Module 7* uses *ovn-trace* and *ovn-nbctl* to debug why pods in the same namespace can not communicate
. *Module 8* uses *ovn-trace* and *ovn-nbctl* to debug why some traffic between namespaces works and some is failing
. *Module 9* uses *ovn-trace* and *ovn-nbctl* to debug why a VirtualMachine on a secondary network can only reach certain external websites
