= OVN-Kubernetes - My VirtualMachine can not access most external addresses
#:prewrap!:

Let us switch gears and take a look at an Openshift Virtualization use case where we have a Virtual Machine using a secondary network interface on a VLAN.

[#theissue]
== Issues with VirtualMachine external access 

The VirtualMachine can only access certain websites and external resources.

[#debugexternalaccess]
== Debug the Traffic Flow

[NOTE]
=====
In the previous modules we provided `ovnkube-trace` examples so you see how to easily run traces in a running OpenShift cluster. As of the wiriting of this lab, the `ovnkube-trace` wrapper does not support VMs or secondary interfaces.
=====

If you think that functionality would be valuable, add your input or customer to the feature request: https://issues.redhat.com/browse/RFE-8186[Debugging ovnkube-trace improvements - add ability to trace VMs on secondary networks]

[#runtrace]
=== Running the Trace

From your execution environment, run the following `ovn-trace`.

. `default.vlan530_external_virt-launcher-external-vm-tfbr4` -> is the OVN datapath which is a logical router or switch associated to the workload
. `inport` -> is the OVN port for instance we are tracing from
. `eth.src` -> source pod mac address
. `eth.dst` -> destination router to switch (rtos) port mac address
. `ip4.src` -> source pod IP address
. `ip4.dst` -> external destination address
. `tcp.dst` -> destination port
. `tcp.src` -> source port

[.wrap,console,role=execute]
----
ovn-trace --ct=new --no-leader-only  --db unix:/var/run/ovn/ovnsb_db.sock br.ex.localnet_ovn_localnet_switch 'inport=="default.vlan530_external_virt-launcher-external-vm-tfbr4" && eth.src==02:a1:3b:00:00:15 && eth.dst==0a:58:0a:81:06:01 && ip4.src==10.6.153.247 && ip4.dst==140.82.113.3 && ip.ttl==64 && tcp.dst==80 && tcp.src==60000'
----

When the `ovn-trace` runs, you get a full accounting of how that packet would traverse the SDN and where it would exit to hit the desired exteral resource.

[source,console]
----
ingress(dp="br.ex.localnet_ovn_localnet_switch", inport="default.vlan530_external_virt-launcher-external-vm-tfbr4")
-------------------------------------------------------------------------------------------------------------------
 0. ls_in_check_port_sec (northd.c:9399): 1, priority 50, uuid fc8d6873
    reg0[15] = check_in_port_sec();
    next;
 4. ls_in_pre_acl (northd.c:6054): ip, priority 100, uuid 6aeebe54
    reg0[0] = 1;
    next;
 6. ls_in_pre_stateful (northd.c:6304): reg0[0] == 1, priority 100, uuid 516d2bfd
    ct_next(dnat);

ct_next(ct_state=new|trk)
-------------------------
 7. ls_in_acl_hint (northd.c:6363): ct.new && !ct.est, priority 7, uuid bd0a37b0
    reg0[7] = 1;
    reg0[9] = 1;
    reg0[1] = 1;
    next;
 8. ls_in_acl_eval (northd.c:7480): ip && !ct.est, priority 1, uuid 59afb818
    next;
10. ls_in_acl_action (northd.c:7297): 1, priority 0, uuid 21f3b456
    reg8[16] = 0;
    reg8[17] = 0;
    reg8[18] = 0;
    next;
20. ls_in_acl_after_lb_action (northd.c:7308): reg8[30..31] == 0, priority 500, uuid 2ad8154b
    reg8[30..31] = 1;
    next(18);
20. ls_in_acl_after_lb_action (northd.c:7308): reg8[30..31] == 1, priority 500, uuid 2b82ad72
    reg8[30..31] = 2;
    next(18);
18. ls_in_acl_after_lb_eval (northd.c:7065): reg8[30..31] == 2 && reg0[7] == 1 && (ip4.dst == 140.82.113.0/24 && inport == @a6086215553377573259), priority 2001, uuid 1e1df3e7
    reg8[16] = 1;
    next;
20. ls_in_acl_after_lb_action (northd.c:7276): reg8[16] == 1, priority 1000, uuid a00e31d8
    reg8[16] = 0;
    reg8[17] = 0;
    reg8[18] = 0;
    reg8[30..31] = 0;
    next;
21. ls_in_stateful (northd.c:8292): reg0[1] == 1 && reg0[13] == 0, priority 100, uuid d386eaaf
    ct_commit { ct_mark.blocked = 0; ct_mark.allow_established = reg0[20]; ct_label.acl_id = reg2[16..31]; };
    next;
28. ls_in_l2_lkup (northd.c:5845): 1, priority 0, uuid 222432ad
    outport = get_fdb(eth.dst);
    next;
29. ls_in_l2_unknown (northd.c:9336): outport == "none", priority 50, uuid 64d6fbdf
    outport = "_MC_unknown";
    output;

multicast(dp="br.ex.localnet_ovn_localnet_switch", mcgroup="_MC_unknown")
-------------------------------------------------------------------------

    egress(dp="br.ex.localnet_ovn_localnet_switch", inport="default.vlan530_external_virt-launcher-external-vm-tfbr4", outport="br.ex.localnet_ovn_localnet_port")
    --------------------------------------------------------------------------------------------------------------------------------------------------------------
         2. ls_out_pre_acl (northd.c:5906): ip && outport == "br.ex.localnet_ovn_localnet_port", priority 110, uuid b92df973
            next;
         3. ls_out_pre_lb (northd.c:5906): ip && outport == "br.ex.localnet_ovn_localnet_port", priority 110, uuid 2c58ff66
            next;
         5. ls_out_acl_hint (northd.c:6363): ct.new && !ct.est, priority 7, uuid 90b5da92
            reg0[7] = 1;
            reg0[9] = 1;
            reg0[1] = 1;
            next;
         6. ls_out_acl_eval (northd.c:7482): ip && !ct.est, priority 1, uuid 5a76004e
            next;
         8. ls_out_acl_action (northd.c:7308): reg8[30..31] == 0, priority 500, uuid 9ba0e4eb
            reg8[30..31] = 1;
            next(6);
         6. ls_out_acl_eval (northd.c:7482): ip && !ct.est, priority 1, uuid 5a76004e
            next;
         8. ls_out_acl_action (northd.c:7308): reg8[30..31] == 1, priority 500, uuid a72c3c38
            reg8[30..31] = 2;
            next(6);
         6. ls_out_acl_eval (northd.c:7482): ip && !ct.est, priority 1, uuid 5a76004e
            next;
         8. ls_out_acl_action (northd.c:7297): 1, priority 0, uuid 2e305a31
            reg8[16] = 0;
            reg8[17] = 0;
            reg8[18] = 0;
            reg8[30..31] = 0;
            next;
        10. ls_out_stateful (northd.c:8297): reg0[1] == 1 && reg0[13] == 0, priority 100, uuid aa3d0cd1
            ct_commit { ct_mark.blocked = 0; ct_mark.allow_established = reg0[20]; ct_label.acl_id = reg2[16..31]; };
            next;
        11. ls_out_check_port_sec (northd.c:5866): 1, priority 0, uuid a87e1d41
            reg0[15] = check_out_port_sec();
            next;
        12. ls_out_apply_port_sec (northd.c:5874): 1, priority 0, uuid 7e9dcb6d
            output;
            /* output to "br.ex.localnet_ovn_localnet_port", type "localnet" */
----
